//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyBudget.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetDBModel : DbContext
    {
        public BudgetDBModel()
            : base("name=BudgetDBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpenseTyp> ExpenseTyps { get; set; }
        public virtual DbSet<Fund> Funds { get; set; }
        public virtual DbSet<FundFrequency> FundFrequencies { get; set; }
        public virtual DbSet<FundSrc> FundSrcs { get; set; }
        public virtual DbSet<FundTyp> FundTyps { get; set; }
    }
}
