//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyBudget.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> SetAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Financial_Year { get; set; }
        public string Assessment_Year { get; set; }
        public Nullable<int> FrequencyId { get; set; }
    }
}
